### ISSUE TITLE
Come Up with 3 Blog Posts ideas

### ISSUE THREAD

**Issue by santiagobasulto** [rmotr-career-services/career-services-eggarcia28#16]
This is another way to show you are active in the programming world. Find something you are interested in, do some research about it, and share your findings! People tend to appreciate articles they find something new and useful from.

**Deliverable:** Come up with 3 ideas of posts to write in the following weeks. Post them as a comment in this issue and close it for review.

`RMOTR: PB#8`

**Comment by eggarcia28** [comment]
1: My Demo Day Project. 

2: I wrote a very small program a while ago. I looked at the code recently and it was not good. I would write about the changes I made while talking about my growth in Python.

3: A future data analysis project. 
3(optional): I could write about why I think people in all fields should learn programming at some level. Currently, I have a friend that is about to learn Python after being a financial analyst for a couple years. So, maybe quick tips to other beginners too.
