### ISSUE TITLE
Set up / Clean up your other social media profiles

### ISSUE THREAD

**Issue by santiagobasulto** [rmotr-career-services/career-services-eggarcia28#17]
It's good to make yourself reachable in other platforms. You can come choose any platform and this is entirely up to you. A few recommendations from our part:
* Twitter
* Facebook
* angel.co
* medium.com
* StackOverflow

**Deliverable:** Once you're done. Post your profiles in this issue and close it for review.

`RMOTR: PB#6`

**Comment by eggarcia28** [comment]
https://twitter.com/egge28  This right now is pretty soccer and music heavy. I have been following data scientists on there. They're pretty good follows. I'd like to add my future findings here, but right now it is not that. 

https://stackexchange.com/users/13588985/eric I barely made this.

I plan on creating a medium profile when I'm ready to post something.
